# Generated by Django 6.0.5 on 2026-05-18 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title_prefix', models.CharField(blank=True, max_length=50, verbose_name='Titul před jménem')),
                ('first_name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('title_suffix', models.CharField(blank=True, max_length=50, verbose_name='Titul za jménem')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Věk')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='Povolání')),
                ('party', models.CharField(blank=True, default='ODS', max_length=100, verbose_name='Strana')),
                ('bio', models.TextField(blank=True, verbose_name='Medailonek')),
                ('priorities', models.TextField(blank=True, verbose_name='Priority')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/', verbose_name='Fotografie')),
                ('is_leader', models.BooleanField(default=False, verbose_name='Lídr kandidátky')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Zobrazit na webu')),
            ],
            options={
                'verbose_name': 'Kandidát',
                'verbose_name_plural': 'Kandidáti',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jméno')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Předmět')),
                ('message', models.TextField(verbose_name='Zpráva')),
                ('is_read', models.BooleanField(default=False, verbose_name='Přečteno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zpráva',
                'verbose_name_plural': 'Zprávy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Název události')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('date', models.DateField(verbose_name='Datum')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='Čas od')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='Čas do')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Místo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Obrázek')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publikováno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Událost',
                'verbose_name_plural': 'Události',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název alba')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name='Obálka')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Datum')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publikováno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fotoalbum',
                'verbose_name_plural': 'Fotoalba',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Nadpis')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('content', models.TextField(verbose_name='Obsah')),
                ('excerpt', models.TextField(blank=True, verbose_name='Krátký popis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Hlavní obrázek')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publikováno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Příspěvek',
                'verbose_name_plural': 'Příspěvky',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název kategorie')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikona (emoji)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Kategorie programu',
                'verbose_name_plural': 'Kategorie programu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Máme rádi Trutnov', max_length=200)),
                ('tagline', models.CharField(default='A co vy?', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_text', models.TextField(blank=True)),
                ('contact_email', models.EmailField(default='barboratomasova@seznam.cz', max_length=254)),
                ('contact_phone', models.CharField(default='775 887 616', max_length=30)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/MameRadiTrutnov/')),
                ('instagram_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(default='© 2026 Máme rádi Trutnov', max_length=300)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Nastavení webu',
                'verbose_name_plural': 'Nastavení webu',
            },
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jméno')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Funkce/titul')),
                ('quote', models.TextField(blank=True, verbose_name='Citát')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='supporters/', verbose_name='Fotografie')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True, verbose_name='Zobrazit')),
            ],
            options={
                'verbose_name': 'Podporovatel',
                'verbose_name_plural': 'Podporovatelé',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Název')),
                ('url', models.URLField(verbose_name='URL videa (YouTube, apod.)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Náhled')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, verbose_name='Publikováno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videa',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Fotografie')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Popisek')),
                ('order', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='web.photoalbum', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Fotografie',
                'verbose_name_plural': 'Fotografie',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Název bodu')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='web.programcategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Bod programu',
                'verbose_name_plural': 'Body programu',
                'ordering': ['category__order', 'order'],
            },
        ),
    ]
